add header and some config
unitedstack/ustackdocstheme pull request #11
Opened 2021-04-29 12:59 UTC by yyt520

2021-05-08 01:42 UTC, hex2dec requested changes
在原来主题基础上进行“重构”，而不是“重写”一个。

2021-05-08 01:42 UTC, hex2dec commented on setup.cfg
> +  ustacktheme = ustackdocstheme.theme.ustacktheme
主题名称为什么要从 ustackdocs 换成 ustacktheme

2021-05-08 01:42 UTC, hex2dec commented on doc/source/conf.py
> +# html_theme = 'ustackdocs'
没用的注释应该去掉，当然我还是困惑为什么要给主题换名称。

2021-05-08 01:42 UTC, hex2dec commented on tox.ini
> +[testenv:docs_theme]
和上面 docs 是重复的。

2021-05-12 02:22 UTC, closed without merging

2021-05-12 02:22 UTC, yyt520 commented
abanded